import { Public_Sans } from "next/font/google";
import "./globals.css";
import NavBar, { NavBarContext, NavBarProvider } from "@/app/_components/NavBar";

import "@/public/style.css";

const public_sans = Public_Sans();

export const metadata = {
 title: {
  template: "Personal Finance App \u2014 %s",
  default:  "Personal Finance App \u2014 Overview",
 },
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
   <head>
    <link rel="stylesheet" href="style.css" />
   </head>
   <body className={public_sans.className}>
    <NavBarProvider>
     <NavBar />
     <main className="content">
      {children}
     </main>
    </NavBarProvider>
   </body>
  </html>
 );
}
